/*
 * Simple calc API
 * This a simple API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * Returns sum of x and y
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void additionGetTest() throws ApiException {
        Float x = null;
        Float y = null;
        Float response = api.additionGet(x, y);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns quotient of x and y
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void divisionGetTest() throws ApiException {
        Float x = null;
        Float y = null;
        Float response = api.divisionGet(x, y);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns product of x and y
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void multiplicationGetTest() throws ApiException {
        Float x = null;
        Float y = null;
        Float response = api.multiplicationGet(x, y);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the difference x and y
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void substractionGetTest() throws ApiException {
        Float x = null;
        Float y = null;
        Float response = api.substractionGet(x, y);

        // TODO: test validations
    }
}
